### ISSUE TITLE
DDL statements

### ISSUE THREAD

**Issue by sjahongir** [mongodb/docs-bi-connector#102]
Hi!
Can I use **DDL statements** (CREATE/DROP/ALTER table)? 
In version 2.3

**Comment by sjahongir** [comment]
I need to execute ddl statements using MySql provider to create/alter/drop mongo database/collection in C#.  Is it possible?

**Comment by steveren** [comment]
Hi @sjahongir,

This isn't really a support forum. For community support, I suggest you try Stackoverflow.

Best regards,

- Steve

**Comment by sjahongir** [comment]
@steveren, Thanks for your suggestion!
